# Site settings
email: 1105249307@qq.com
baseurl: "https://zhangjing9898.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: zhangjing blog
description: zhangjing9898 blog
url: "https://zhangjing9898.github.io"
twitter_username: zhangjingbibibi
default_img: https://unsplash.it/200/300?image=999

# Profile settings
name: zhangjingbibibi
profile_img: https://unsplash.it/2000/1200?image=999
profile: 前段时间一直在读Harry Potter，大概印象最深的是这句话：“Working hard is important. But there is something that matters even more, believing in yourself.” 努力很重要，然而更重要的是：相信自己。把这句分享给大家
social:
  github:
  
# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
